#!/usr/bin/env bash
set -e

docker run -v "$REPO_DIR":/gsl zeromqorg/zproject project.xml

if [[ $(git diff) ]]; then
    git diff
    echo "There are diffs between current code and code generated by zproject!"
    exit 1
fi
if [[ $(git status -s) ]]; then
    git status -l
    echo "zproject generated new files!"
    exit 1
fi
