/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/

#ifndef QML_MALAMUTE_PLUGIN_H
#define QML_MALAMUTE_PLUGIN_H

#include <QQmlExtensionPlugin>
#include <qqml.h>

class QmlMlmProto;
class QmlMlmProtoAttached;
class QmlMlmClient;
class QmlMlmClientAttached;

#include "QmlMlmProto.h"
#include "QmlMlmClient.h"

class QmlMalamutePlugin : public QQmlExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA (IID "org.qt-project.Qt.QQmlExtensionInterface")
    
public:
    void registerTypes (const char *uri)
    {
        qmlRegisterType<QmlMlmProto> (uri, 1, 0, "QmlMlmProto");
        qmlRegisterType<QmlMlmProtoAttached>();
        qmlRegisterType<QmlMlmClient> (uri, 1, 0, "QmlMlmClient");
        qmlRegisterType<QmlMlmClientAttached>();
    };
};

#endif

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
