################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
from . import utils
SUCCESS = 200 #
FAILED = 300 #
COMMAND_INVALID = 500 #
NOT_IMPLEMENTED = 501 #
INTERNAL_ERROR = 502 #
CONNECTION_OPEN = 1 #
CONNECTION_PING = 2 #
CONNECTION_PONG = 3 #
CONNECTION_CLOSE = 4 #
STREAM_WRITE = 5 #
STREAM_READ = 6 #
STREAM_SEND = 7 #
STREAM_DELIVER = 8 #
MAILBOX_SEND = 9 #
MAILBOX_DELIVER = 10 #
SERVICE_SEND = 11 #
SERVICE_OFFER = 12 #
SERVICE_DELIVER = 13 #
OK = 14 #
ERROR = 15 #
CREDIT = 16 #
CONFIRM = 17 #
STREAM_CANCEL = 18 #
from .MlmProto import *
from .MlmClient import *
