#!/usr/bin/env bash
set -ex
docker run -e GSL_BUILD_DIR=/code/src -v "$REPO_DIR":/code zeromqorg/zproto -zproject:1 -q mlm_proto.xml
docker run -e GSL_BUILD_DIR=/code/src -v "$REPO_DIR":/code zeromqorg/zproto -zproject:1 -q mlm_client.xml
docker run -e GSL_BUILD_DIR=/code/src -v "$REPO_DIR":/code zeromqorg/zproto -zproject:1 -q mlm_server.xml

# display version to try to understand why code below works on my machine
# but not on Travis
git --version
if [[ $(git --no-pager diff -w api/*) ]]; then
    git --no-pager diff -w api/*
    echo "There are diffs between current code and code generated by zproto!"
    exit 1
fi
if [[ $(git status -s api) ]]; then
    git status -l api
    echo "zproto generated new files!"
    exit 1
fi
