################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
NAME        = "malamute"
VERSION     = "1.2.0"
LICENSE     = "mpl-2.0"
DESCRIPTION = """Python bindings of: zeromq message broker"""
URL         = "https://github.com/zeromq/malamute"
PACKAGES    = ["malamute"]
REQUIRES    = [
    "czmq",
]
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
