################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
from setuptools import setup

setup(
    name = "malamute",
    version = "1.1.0",
    license = "mpl-2.0",
    description = """Python bindings of: zeromq message broker""",
    url = "https://github.com/zeromq/malamute",
    packages = ["malamute"],
    install_requires = [
        "czmq",
    ],
)
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
