/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
#ifndef Q_MLM_H
#define Q_MLM_H

#include <QObject>
#include <QString>
#include <malamute.h>

#if defined(Q_OS_WIN)
#  if !defined(QT_MLM_EXPORT) && !defined(QT_MLM_IMPORT)
#    define QT_MLM_EXPORT
#  elif defined(QT_MLM_IMPORT)
#    if defined(QT_MLM_EXPORT)
#      undef QT_MLM_EXPORT
#    endif
#    define QT_MLM_EXPORT __declspec(dllimport)
#  elif defined(QT_MLM_EXPORT)
#    undef QT_MLM_EXPORT
#    define QT_MLM_EXPORT __declspec(dllexport)
#  endif
#else
#  define QT_MLM_EXPORT
#endif

//  Opaque class structures to allow forward references
class QMlmProto;
class QMlmClient;
class QZsock;
class QZframe;
class QZmsg;
class QZactor;

//  Public API classes
#include "qmlmproto.h"
#include "qmlmclient.h"
#include "qzsock.h"
#include "qzframe.h"
#include "qzmsg.h"
#include "qzactor.h"

#endif //  Q_MLM_H
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
