#! /bin/bash
#
#   Run selftests and check memory

MAIN=mlm_selftest
VG="valgrind --tool=memcheck --leak-check=full --show-reachable=yes --suppressions=valgrind.supp"

make code
gcc -g -o $MAIN \
    $MAIN.c \
    mlm_msg.c mlm_server.c mlm_client.c \
    -lczmq -lzmq -lzyre -luuid -lsodium
test $? -ne 0 && exit
$VG ./$MAIN
rm -f vgcore.*
