#############################################################################
#   THIS FILE IS GENERATED BY ZPROJECT, DO NOT EDIT EXCEPT EXPERIMENTALLY   #
#   Please read the README.txt file if you like to do permanent changes.    #
#############################################################################

BASE_PATH := $(call my-dir)
APP_PLATFORM = android-10

LOCAL_PATH := $(BASE_PATH)

#   Info for libzmq

include $(CLEAR_VARS)
LOCAL_MODULE := zmq
LOCAL_SRC_FILES := libzmq.so
include $(PREBUILT_SHARED_LIBRARY)

#   Build malamute

include $(CLEAR_VARS)
LOCAL_MODULE := malamute
LOCAL_C_INCLUDES := ../../include $(LIBZMQ)/include
LOCAL_SRC_FILES := mlm_msg.c mlm_client.c mlm_server.c mlm_stream_simple.c zbits.c
LOCAL_SHARED_LIBRARIES := zmq
include $(BUILD_SHARED_LIBRARY)

#############################################################################
#   THIS FILE IS GENERATED BY ZPROJECT, DO NOT EDIT EXCEPT EXPERIMENTALLY   #
#   Please read the README.txt file if you like to do permanent changes.    #
#############################################################################
